KERNEL_TARGET = xdpfw_kern
USER_TARGET = xdpfw_user

# USER_TARGET_DEPS = layer4_user.h $(EXTRA_HEADERS)
# KERNEL_TARGET_DEPS = $(EXTRA_HEADERS)
#
# CFLAGS = "-I../00-common/"

include ../common/makerules
