KERNEL_TARGET = xdpfw_kern
KERNEL_TARGET_DEPS = xdpfw_kern_l2.h xdpfw_kern_l3.h xdpfw_kern_l4.h xdpfw_kern_utils.h common.h

USER_TARGET = xdpfw_user
USER_TARGET_DEPS = xdpfw_user.h common.h

include ../common/makerules
